version: '3'
services:
  baselapp:
    build:
       context: ./sap2py
       dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ${ENV_FILE}
  frontend:
    build:
      context: ./sap2py-fe
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - baselapp
    environment:
      - SAP2PY_URL=http://baselapp:5000

