version: '3'
services:
  walter-be:
    build:
       context: ./sap2py
       dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: global_vars.env
  frontend:
    build:
      context: ./sap2py-fe
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - walter-be
      - keycloak
    environment:
      - SAP2PY_URL=http://walter-be:5000
      - KEYCLOAK_URL=http://keycloak:8080/auth
  keycloak:
    build:
       context: ./keycloak
       dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: global_vars.env
    depends_on:
      - mysql
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/tmp/import"]
  mysql:
    build:
       context: int-tests/db
       dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file: global_vars.env
  test:
     build:
        context: ./int-tests
        dockerfile: Dockerfile
     env_file: global_vars.env
     depends_on:
       - walter-be
       - mysql
     command: >
         sh -c "dockerize -wait tcp://mysql:3306 -timeout 30s &&
                dockerize -wait http://walter-be:5000 -timeout 30s &&
                behave"

